<a href="https://colab.research.google.com/github/FuturisticLover123/labs/blob/main/lab8/lab8solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [222]:
# task1
from sklearn.metrics import accuracy_score
import numpy as np

class NBC:
  def __init__(self):
    pass


  def pxy(self, ditribution, x, cld):
    if ditribution == "gaussian":
      m, q = cld
      return (1 / (q * np.sqrt(2 * np.pi)) ) * np.exp(-((x - m)**2 / (2 * q**2)))



  def get_cl_data(self, distibution, x, y):
    if distibution == "gaussian":
      return np.mean(x), np.std(x)

  def fit(self, x, y, feature_distribution: dict = {}):
    self.x, self.y = x, y
    self.classes = list(set(y))
    self.feature_distribution = feature_distribution
    indexes = { clas : np.where(y == clas)[0] for clas in self.classes }

    self.prior_probability = { clas : len(indexes[clas]) / len(y) for clas in indexes }

    self.classifying_data = dict()
    for clas in self.classes:
      self.classifying_data[clas] = self.classifying_data.get(clas, dict())
      for feature in range(x.shape[1]):
        distribution = self.feature_distribution.get(feature, "gaussian")
        self.classifying_data[clas][feature] = self.get_cl_data(distribution, x[indexes[clas]][: ,feature], y[indexes[clas]])
    return self

  def classify(self, x):
    weights = { clas : np.log(self.prior_probability[clas]) for clas in self.classes }
    for clas in self.classes:
      for feature in range(len(x)):
        distribution = self.feature_distribution.get(feature, "gaussian")
        weights[clas] += np.log( self.pxy(distribution, x[feature], self.classifying_data[clas][feature]) )
    return max(weights, key=weights.get)

  def predict(self, x):
    return np.array([self.classify(x_i) for x_i in x])

  def score(self, x, y):
    y_pred = self.predict(x)
    return accuracy_score(y, y_pred)

  def get_params(self, deep=True):
    return {
    }

  def set_params(self, **params):
    for key, value in params.items():
        setattr(self, key, value)
    return self


In [223]:
from sklearn.datasets import make_classification

In [224]:
x,y = make_classification(n_samples = 1000,n_features = 30,n_redundant=20)

In [225]:
NBC().fit(x, y).score(x, y)

0.909

In [226]:
#task2

In [227]:
import pandas as pd

In [79]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [80]:
!kaggle datasets download -d valakhorasani/mobile-device-usage-and-user-behavior-dataset -p /content/sample_data/lab8
!unzip /content/sample_data/lab8/mobile-device-usage-and-user-behavior-dataset.zip -d /content/sample_data/lab8

Dataset URL: https://www.kaggle.com/datasets/valakhorasani/mobile-device-usage-and-user-behavior-dataset
License(s): apache-2.0
  0% 0.00/11.3k [00:00<?, ?B/s]
100% 11.3k/11.3k [00:00<00:00, 20.4MB/s]
Archive:  /content/sample_data/lab8/mobile-device-usage-and-user-behavior-dataset.zip
  inflating: /content/sample_data/lab8/user_behavior_dataset.csv  


In [98]:
data = pd.read_csv("/content/sample_data/lab8/user_behavior_dataset.csv").dropna()

In [99]:
data.head(3)

User ID    Device Model Operating System  App Usage Time (min/day)  \
0        1  Google Pixel 5          Android                       393   
1        2       OnePlus 9          Android                       268   
2        3    Xiaomi Mi 11          Android                       154   

   Screen On Time (hours/day)  Battery Drain (mAh/day)  \
0                         6.4                     1872   
1                         4.7                     1331   
2                         4.0                      761   

   Number of Apps Installed  Data Usage (MB/day)  Age  Gender  \
0                        67                 1122   40    Male   
1                        42                  944   47  Female   
2                        32                  322   42    Male   

   User Behavior Class  
0                    4  
1                    3  
2                    2

In [100]:
data["Device Model"] = data["Device Model"].apply(lambda x: x.split(' ')[0])

In [105]:
x = pd.get_dummies(data, columns = ['Device Model', 'Operating System', 'Gender']).drop(columns = ['User ID', 'User Behavior Class']).astype(float).values
y = data['User Behavior Class'].values

In [106]:
from sklearn.model_selection import cross_val_score

In [109]:
model = NBC()
cross_val_score(model, x, y, cv=10).mean()

1.0

In [ ]:
#task 3

In [172]:
data = pd.read_csv('/content/sample_data/lab8/spam.csv', encoding='ISO-8859-1').drop(columns = ['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4']).dropna()

In [173]:
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer
import nltk

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [228]:
def preprocess_text(text):
    text = text.lower()

    text = re.sub(r'[^\w\s]', '', text)

    words = word_tokenize(text)

    stop_words = set(stopwords.words('english'))
    words = [word for word in words if word not in stop_words]

    lemmatizer = WordNetLemmatizer()
    words = [lemmatizer.lemmatize(word) for word in words]

    stemmer = PorterStemmer()
    words = [stemmer.stem(word) for word in words]

    return ' '.join(words)


text = "I running love programming in Python, and I enjoy solving coding challenges!"

processed_text = preprocess_text(text)
print(processed_text)


run love program python enjoy solv code challeng


In [229]:
data['v2'] = data['v2'].apply(preprocess_text)

In [230]:
x = data['v2'].values
y = data['v1'].map({ 'spam' : 0, 'ham':1 }).values

In [231]:
y

array([1, 1, 0, ..., 1, 1, 1])

In [279]:
class SpamNBC(NBC):
  def __init__(self, alpha=1):
    super().__init__()
    self.alpha = alpha

  def fit(self, x, y):
    self.classes = list(set(y))
    indexes = { clas : np.where(y == clas)[0] for clas in self.classes }

    self.prior_probability = { clas : len(indexes[clas]) / len(y) for clas in indexes }
    self.words_in_class = dict()


    self.classifying_data = dict()
    for clas in self.classes:
      self.words_in_class[clas] = 0
      self.classifying_data[clas] = dict()
      for x_i in x[indexes[clas]]:
        self.words_in_class[clas] += len(x_i.split(' '))

        for word in x_i.split(' '):
          self.classifying_data[clas][word] = self.classifying_data[clas].get(word, 0) + 1

    self.n = len(set(" ".join(x).split(' ')))

    return self

  def classify(self, x):
    weights = { clas : np.log(self.prior_probability[clas]) for clas in self.classes }
    for clas in self.classes:
      for x_i in x:
        weights[clas] += np.log( (self.classifying_data[clas].get(x_i, 0) + self.alpha)  / (self.words_in_class[clas] + 1000* self.alpha))
    return max(weights, key=weights.get)


In [280]:
model = SpamNBC(alpha = 0).fit(x, y)


In [281]:
model.score(x, y)

<ipython-input-279-476a4a9fea29>:32: RuntimeWarning: divide by zero encountered in log
  weights[clas] += np.log( (self.classifying_data[clas].get(x_i, 0) + self.alpha)  / (self.words_in_class[clas] + 1000* self.alpha))


0.1362167982770998

In [255]:
model.predict(x[0])

<ipython-input-250-32c9330fe6bd>:28: RuntimeWarning: divide by zero encountered in log
  weights[clas] += np.log( (self.classifying_data[clas].get(x_i, 0) + self.alpha)  / (self.class_sizes[clas] + self.n* self.alpha))


array([1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0])

In [217]:
y[0]

1

In [237]:
np.unique(np.array([1,2,1,1,2]), return_counts=True)

(array([1, 2]), array([3, 2]))