# Task 1

In [1]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
import numpy as np
import numpy.linalg as alg
import matplotlib.pyplot as plt
import pandas as pd
import numdifftools as nd
import pandas as pd


In [2]:
A = np.random.randint(10,size =(10,10))
x = np.arange(0,10)

In [3]:
def func(x): 
    return np.dot(np.dot(x.T,A),x)

In [4]:
def f1(x):
    return np.dot(x.T, np.dot(A, x))

def f2(x):
    return np.dot(a.T, x)

def xtx(x):
    return np.dot(x.T, x)

def lndetx(X_flat):
    X = X_flat.reshape(3, 3)
    return np.log(np.linalg.det(X))

In [5]:
(nd.Gradient(func)(x), np.dot(A + A.T,x))

(array([567., 304., 500., 442., 336., 384., 199., 331., 281., 249.]),
 array([567, 304, 500, 442, 336, 384, 199, 331, 281, 249]))

In [6]:
#xtx
print(2 * x)
print(nd.Gradient(xtx)(x))

[ 0  2  4  6  8 10 12 14 16 18]
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]


In [127]:
X = np.random.randint(100,size =(3,3))

grad_analytic = np.linalg.inv(X).transpose()

grad_numerical = nd.Gradient(lndetx)(X.flatten()).reshape(3, 3)

print(grad_analytic)


print(grad_numerical)

[[-0.01203895 -0.04317154  0.02806533]
 [ 0.04232804  0.00529101 -0.01587302]
 [-0.11210797  0.06931984  0.0384173 ]]
[[-0.01203895 -0.04317154  0.02806533]
 [ 0.04232804  0.00529101 -0.01587302]
 [-0.11210797  0.06931984  0.0384173 ]]


# Task 2

In [120]:
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt


class LinRegression:
    def __init__(self,x,y):
        self.x_train, self.x_test, self.y_train, self.y_test = train_test_split(x, y, test_size=0.2, random_state=422)
        self.l, self.bazis, self.features, self.w = 0, None, None, None
    
    def set_bazis(self, bazis):
        self.bazis = bazis
    
    def set_features(self,features):
        self.features = features

    def set_l(self,l):
        self.l = l
        
    def apply_features(self,x):
        return x if self.features is None else self.features(x)
    
#     def get_matrq(self):
#         features = self.apply_features(self.x_train)
#         bazis = np.array([lambda x,i=i:x[i] for i in range(features.shape[1])]) if self.bazis is None else self.bazis
#         q = np.array([[f(x) for f in bazis] for x in features])
#         return q
        
    def get_matrq(self):
        return gausian_bazis(self.x_train)
    
    def get_w(self):
        if self.w is not None:
            return self.w
        q = self.get_matrq()
        self.w =  np.dot(np.dot(alg.inv(np.dot(q.transpose(),q) + np.diag([self.l] * q.shape[1])),q.transpose()),self.y_train)
        return self.w

    def apply_weights(self,x):
        w = self.get_w() if self.w is None else self.w
        features = self.apply_features(x)
        return np.array([np.dot(i,w) for i in features])
    
    def get_accuracy(self,x=None,y=None):
        fx=self.apply_weights(self.x_test if x is None else x)
        y_acc =self.y_test if y is None else y
        return 1-(np.dot(y_acc - fx,y_acc - fx)) / (np.dot(y_acc - np.mean(y_acc),y_acc - np.mean(y_acc)))
    
    def clear(self):
        self.w,features,self.bazis = None, None, None
        
    def validate(self,features: list,show=False):
        self.clear()
        train,test = list(), list()
        for feature in features:
            self.clear()
            self.set_features(feature)
            train.append(self.get_accuracy(self.x_train,self.y_train))
            test.append(self.get_accuracy())
        if show:
            plt.plot(train,'r-o')
            plt.plot(test,'b-o')
            plt.legend(['Train', 'Test'])
            plt.show()

        return train,test

In [102]:
def GausianBasis(shape: int):
    return np.array([lambda x,i=i : np.exp(-((x - x[i])**2).sum()) for i in range(shape)])

In [11]:
x,y = make_regression(n_samples=1000,n_features=features)

NameError: name 'make_regression' is not defined

In [64]:
model = LinearRegression(fit_intercept=True)
model.fit(x,y)
model.score(x,y)

0.6369116857335633

In [ ]:
features = 4

reg = LinRegression(x,y)
reg.set_l(1)
reg.set_bazis(GausianBasis(features))
reg.get_accuracy()

In [ ]:
plt.scatter(x,y)

In [ ]:
def show(x,y,f):
    x_i = np.linspace(x.min(),x.max(),1000)
    plt.plot(x_i,f(np.array(x_i)[:, np.newaxis]),'r')
    plt.scatter(x,y)

In [ ]:
rng = np.random.RandomState(1) # задаём искусственные данные
x = (10 * rng.rand(50))
y = 2*x+rng.randn(50)


In [ ]:
plt.scatter(x,y)


In [ ]:
reg = LinRegression(x.reshape(-1,1),y)
reg.set_features(PolynomialFeatures(degree=10).fit_transform)

In [ ]:
reg.get_accuracy()

In [ ]:
show(x,y,reg.apply_weights)

In [ ]:
reg.get_accuracy()

In [ ]:
reg.get_w();

In [ ]:
reg.get_accuracy()

In [ ]:
m = x.T.mean(axis=1)
m

In [ ]:
((x - m)**2).mean(axis=0)

In [ ]:
np.mean?

In [66]:
dta = pd.read_csv("1553768847-housing.csv").dropna()
x = dta.values[:,:8]
y = dta.values[:,9]

In [67]:
reg = LinRegression(x,y)
reg.set_features(PolynomialFeatures(degree=1).fit_transform)

In [68]:
reg.get_w()

array([-3607924.9514747295, -42901.07830781874, -42496.36012230831,
       1180.2947638637581, -8.784978676703167, 124.44906602767767,
       -36.64953626344854, 35.6612605894491, 40445.72798818309],
      dtype=object)

In [69]:
reg.get_accuracy()

0.6475421817245478

In [16]:
rg = LinearRegression(fit_intercept=False)

rg.fit(PolynomialFeatures(degree=1).fit_transform(x),y)
rg.coef_

array([-3.58539575e+06, -4.27301205e+04, -4.25097369e+04,  1.15790031e+03,
       -8.24972507e+00,  1.13820707e+02, -3.83855780e+01,  4.77013513e+01,
        4.02975217e+04])

In [72]:
from sklearn.datasets import make_regression

In [115]:
x,y = make_regression(100,3)

In [ ]:
Гаусовы базисные функции

In [95]:

def gaussian_basis(x, mu, sigma):
    return np.exp(-0.5 * np.sum(((x - mu) / sigma) ** 2, axis=1))

def gausian_bazis(X):
    n,d = X.shape
    centers = np.tile(np.linspace(-5,5,d),(d,1)).transpose()
    sigma = 0.5
    
    # Функция для вычисления многомерных Гауссовых базисных функций
    def gaussian_basis(x, mu, sigma):
        return np.exp(-0.5 * np.sum(((x - mu) / sigma) ** 2, axis=1))

    # Построение матрицы признаков
    Phi = np.ones((n, d + 1))
    for j in range(d):
        Phi[:, j + 1] = gaussian_basis(X, centers[j], sigma)
        
    return Phi 

    

In [85]:
gausian_bazis(x)

array([[1.00000000e+000, 7.83529523e-276, 2.08452188e-180, ...,
        3.08496546e-058, 6.13357709e-113, 4.36049978e-189],
       [1.00000000e+000, 1.74157312e-215, 1.97846852e-132, ...,
        1.77497001e-084, 1.50692237e-151, 4.57456346e-240],
       [1.00000000e+000, 2.49358245e-206, 4.64655435e-125, ...,
        8.11917757e-088, 1.13065929e-156, 5.63002590e-247],
       ...,
       [1.00000000e+000, 7.12764247e-243, 7.36499261e-153, ...,
        3.74169214e-063, 2.88939481e-123, 7.97819494e-205],
       [1.00000000e+000, 1.91880117e-188, 4.08460162e-112, ...,
        1.58637325e-104, 2.52369890e-178, 1.43558402e-273],
       [1.00000000e+000, 5.15808846e-221, 1.72979069e-137, ...,
        1.02697401e-086, 2.57381097e-153, 2.30649630e-241]])

In [116]:
X_input = np.random.uniform(-3, 3, (1000, 5))

In [117]:
X_input

array([[ 1.90111473,  0.82308137, -1.9299483 , -0.59613875, -1.46589781],
       [-2.25746718, -2.16423045,  2.47361613,  1.61581337, -0.56978607],
       [-0.04164526, -0.52539275,  1.7174843 , -2.27786107,  0.7286371 ],
       ...,
       [-0.03548479, -2.87096228,  2.43923164, -0.78858678, -2.82811018],
       [ 2.63426467,  0.6587729 ,  2.60277079, -0.39588878, -0.76930239],
       [-2.14426387,  0.71181352,  0.2562953 ,  0.34231689, -2.12378425]])

In [121]:
model = LinRegression(x,y)
model.set_l(10)
model.get_accuracy()

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)