<a href="https://colab.research.google.com/github/FuturisticLover123/labs/blob/main/lab2/solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#task1

In [227]:
pip install numdifftools

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.2/100.2 kB 4.1 MB/s eta 0:00:00


In [228]:
import numdifftools as nd

In [229]:
A = np.random.randint(10,size =(10,10))
x = np.arange(0,10)
def func(x):
    return np.dot(np.dot(x.T,A),x)

In [231]:
(nd.Gradient(func)(x), np.dot(A + A.T,x))

(array([474., 518., 359., 448., 495., 381., 432., 378., 416., 341.]),
 array([474, 518, 359, 448, 495, 381, 432, 378, 416, 341]))

In [232]:
#xtx
print(2 * x)
print(nd.Gradient(xtx)(x))

[ 0  2  4  6  8 10 12 14 16 18]
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]


In [ ]:
#task2

In [67]:
import numpy as np

class LinearRegression:
  def __init__(self):
    pass

  def fit(self, x, y):
    self.coef_ = np.linalg.inv(x.T @ x) @ x.T @ y
    return self

  def score(self, x, y):
    out = self.predict(x)
    return 1 - ((y - out) @ (y - out)) / ((y - y.mean()) @ (y - y.mean()))

  def predict(self,x):
    return x @ self.coef_

In [126]:
from sklearn.datasets import make_regression
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split

In [134]:
#тестовые данные
x,y = make_regression(n_samples=100, n_features = 10)
x_train, x_test, y_train, y_test = train_test_split(x,y)
LinearRegression().fit(x_train,y_train).score(x_test,y_test)

1.0

In [140]:
poly = PolynomialFeatures(degree = 3)

In [70]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

cp: cannot stat 'kaggle.json': No such file or directory
chmod: cannot access '/root/.kaggle/kaggle.json': No such file or directory


In [56]:
!kaggle datasets download -d aryansingh2001/fish-csv -p /content/sample_data/lab2
!unzip /content/sample_data/lab2/fish-csv.zip -d /content/sample_data/lab2

Dataset URL: https://www.kaggle.com/datasets/aryansingh2001/fish-csv
License(s): unknown
  0% 0.00/2.39k [00:00<?, ?B/s]
100% 2.39k/2.39k [00:00<00:00, 6.72MB/s]
Archive:  /content/sample_data/lab2/fish-csv.zip
  inflating: /content/sample_data/lab2/Fish.csv  


In [71]:
data = pd.read_csv("/content/sample_data/lab2/Fish.csv").dropna()

In [86]:
data.head(2)

Species  Weight  Length1  Length2  Length3  Height   Width
0   Bream   242.0     23.2     25.4     30.0   11.52  4.0200
1   Bream   290.0     24.0     26.3     31.2   12.48  4.3056

In [85]:
x = pd.get_dummies(data, columns = ["Species"]).astype(float).drop(columns = ["Weight"]).values
y = data["Weight"].values
x_train, x_test, y_train, y_test = train_test_split(x,y)
LinearRegression().fit(x_train,y_train).score(x_test,y_test)

0.9360849020585846

In [87]:
!kaggle datasets download -d nikhil7280/student-performance-multiple-linear-regression -p /content/sample_data/lab2
!unzip /content/sample_data/lab2/student-performance-multiple-linear-regression.zip -d /content/sample_data/lab2

Dataset URL: https://www.kaggle.com/datasets/nikhil7280/student-performance-multiple-linear-regression
License(s): other
  0% 0.00/48.5k [00:00<?, ?B/s]
100% 48.5k/48.5k [00:00<00:00, 14.2MB/s]
Archive:  /content/sample_data/lab2/student-performance-multiple-linear-regression.zip
  inflating: /content/sample_data/lab2/Student_Performance.csv  


In [106]:
data = pd.read_csv("/content/sample_data/lab2/Student_Performance.csv").dropna()
data["Extracurricular Activities"] = data["Extracurricular Activities"].replace({'Yes': 1, 'No': 0})
data.head(2)

<ipython-input-106-7f3f614f424a>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["Extracurricular Activities"] = data["Extracurricular Activities"].replace({'Yes': 1, 'No': 0})


Hours Studied  Previous Scores  ...  Sample Question Papers Practiced  Performance Index
0              7               99  ...                                 1               91.0
1              4               82  ...                                 2               65.0

[2 rows x 6 columns]

In [108]:
x = data.drop(columns = ["Performance Index"]).values
y = data["Performance Index"].values
x_train, x_test, y_train, y_test = train_test_split(x,y)
LinearRegression().fit(x_train,y_train).score(x_test,y_test)

0.9079123364178154

In [111]:
!kaggle datasets download -d shibumohapatra/house-price -p /content/sample_data/lab2
!unzip /content/sample_data/lab2/house-price.zip -d /content/sample_data/lab2

Dataset URL: https://www.kaggle.com/datasets/shibumohapatra/house-price
License(s): GNU Lesser General Public License 3.0
house-price.zip: Skipping, found more recently modified local copy (use --force to force download)
Archive:  /content/sample_data/lab2/house-price.zip
  inflating: /content/sample_data/lab2/1553768847-housing.csv  


In [142]:
data = pd.read_csv("/content/sample_data/lab2/1553768847-housing.csv").dropna()
data.head(2)

longitude  latitude  housing_median_age  ...  median_income  ocean_proximity  median_house_value
0    -122.23     37.88                  41  ...         8.3252         NEAR BAY              452600
1    -122.22     37.86                  21  ...         8.3014         NEAR BAY              358500

[2 rows x 10 columns]

In [157]:
x = pd.get_dummies(data, columns = ["ocean_proximity"]).drop(columns =["median_house_value"]).astype(float).values
y = data["median_house_value"].values
x_train, x_test, y_train, y_test = train_test_split(x,y)
print(LinearRegression().fit(x_train,y_train).score(x_test,y_test))

0.6412809023434756


In [161]:
poly = PolynomialFeatures(degree=2)
# не может поситать обратную матрицу
#нужен ркгуляризатор
x_train, x_test, y_train, y_test = train_test_split(poly.fit_transform(x),y)
#print(LinearRegression().fit(x_train,y_train).score(x_test,y_test))

In [ ]:
# доп

In [217]:
gaus_kernel = lambda x: np.exp(-((x - np.mean(x, axis = 0)) ** 2 / (2* np.std(x, axis=0)**2)))

In [218]:
gaus = gaus_kernel(x)
LinearRegression().fit(gaus,y).score(gaus,y)

0.2661802551602369

In [219]:
np.random.seed(42)
x = np.random.rand(100, 1) * 10  # 100 случайных значений в диапазоне [0, 10]
y = A * np.exp(B * X.squeeze())

In [220]:
LinearRegression().fit(x,y).score(x,y)

0.7368685722353092

In [221]:
LinearRegression().fit(gaus_kernel(x),y).score(gaus_kernel(x),y)

0.2661802551602369